[tool.poetry]
name = "ssb-klass-python"
version = "0.1.0"
description = "A Python package built on top of KLASS's API for retrieving classifications, codes, correspondances etc."
authors = ["Carl Corneil <cfc@ssb.no>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
dapla-toolbelt = "^1.3.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
ipykernel = "^6.15.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
