[tool.poetry]
name = "ssb-klass-python"
version = "0.0.7"
description = "A Python package built on top of KLASS's API for retrieving classifications, codes, correspondences etc."
authors = ["Carl Corneil <cfc@ssb.no>"]
license = "MIT"
readme = "README.md"
packages = [{include = "klass"}]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
dapla-toolbelt = ">=1.3.2"
python-dateutil = ">=2.8.2"
toml = ">=0.10.2"
ipywidgets = ">=8.0.6"
pandas = ">=1.5.3"
requests = ">=2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
ipykernel = "^6.15.3"
pre-commit = "^2.20.0"
autoflake = "^1.7.6"
pep8-naming = "^0.13.2"
pyupgrade = "^3.1.0"
isort = "^5.10.1"
flake8-logging-format = "^0.8.1"
flake8-eradicate = "^1.4.0"
flake8-debugger = "^4.1.2"
flake8-comprehensions = "^3.10.0"
flake8-builtins = "^2.0.0"
flake8-bugbear = "^22.9.23"
flake8 = "^5.0.4"
bump2version = "^1.0.1"
pytest-cov = "^4.0.0"
mypy = "^0.982"
pyproject-flake8 = "^5.0.4.post1"
pre-commit-hooks = "^4.4.0"
nox = "^2023.4.22"
nox-poetry = "^1.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
skip_gitignore = true
lines_after_imports = 2
